-- Начальные данные. Выполняется после миграции (или автоматически через `supabase db reset`).
-- Сгенерировано скриптом tool/gen_catalog_data.py (вместе с lib/data/mock_data.dart).

insert into public.wineries (id, name, latitude, longitude, region, founded_year, description) values
  (1, 'Château Vartely', 47.3833, 28.8167, 'Codru · Orhei', null,
   jsonb_build_object('ru', 'Современная винодельня у Орхея, в зоне Кодру. При ней работает туристический комплекс с гостиницей и рестораном.', 'ro', 'Vinărie modernă lângă Orhei, în zona Codru, cu un complex turistic care include hotel și restaurant.', 'en', 'A modern winery near Orhei in the Codru region, with a tourist complex that includes a hotel and a restaurant.')),
  (2, 'Château Purcari', 46.525, 29.865, 'Ștefan Vodă · Purcari', 1827,
   jsonb_build_object('ru', 'Одна из старейших виноделен Молдовы, основана в 1827 году на юге страны. Известна красным купажом Negru de Purcari.', 'ro', 'Una dintre cele mai vechi vinării din Moldova, fondată în 1827 în sudul țării. Cunoscută pentru cupajul roșu Negru de Purcari.', 'en', 'One of Moldova''s oldest wineries, founded in 1827 in the south of the country. Known for its red blend Negru de Purcari.')),
  (3, 'Cricova', 47.1386, 28.862, 'Codru · Cricova', 1952,
   jsonb_build_object('ru', 'Знаменита подземными винными галереями протяжённостью более 100 километров — настоящий винный город под землёй.', 'ro', 'Renumită pentru galeriile subterane de peste 100 de kilometri — un adevărat oraș al vinului sub pământ.', 'en', 'Famous for its underground wine galleries stretching over 100 kilometres — a true wine city beneath the ground.')),
  (4, 'Mileștii Mici', 46.905, 28.828, 'Codru · Ialoveni', 1969,
   jsonb_build_object('ru', 'Подземные галереи с огромной коллекцией вин, которая занесена в Книгу рекордов Гиннесса как крупнейшая в мире.', 'ro', 'Galerii subterane cu o colecție imensă de vinuri, înscrisă în Cartea Recordurilor Guinness drept cea mai mare din lume.', 'en', 'Underground galleries holding a vast wine collection listed in the Guinness World Records as the largest in the world.')),
  (5, 'Castel Mimi', 46.89, 29.305, 'Codru · Bulboaca', 1893,
   jsonb_build_object('ru', 'Винодельня в замке, построенном в конце XIX века Константином Мими. Сегодня здесь также ресторан и гостиница.', 'ro', 'Vinărie într-un castel construit la sfârșitul secolului XIX de Constantin Mimi, astăzi cu restaurant și hotel.', 'en', 'A winery in a castle built in the late 19th century by Constantin Mimi, now also home to a restaurant and a hotel.')),
  (6, 'Asconi', 46.825, 29.09, 'Codru · Puhoi', null,
   jsonb_build_object('ru', 'Семейная винодельня в селе Пуой, недалеко от Кишинёва, с рестораном в традиционном молдавском стиле.', 'ro', 'Vinărie de familie în satul Puhoi, aproape de Chișinău, cu un restaurant în stil tradițional moldovenesc.', 'en', 'A family winery in the village of Puhoi, near Chișinău, with a restaurant in traditional Moldovan style.')),
  (7, 'Et Cetera', 46.423, 29.93, 'Ștefan Vodă · Crocmaz', null,
   jsonb_build_object('ru', 'Небольшая семейная винодельня в селе Крокмаз на юге Молдовы, в регионе Штефан-Водэ.', 'ro', 'Vinărie mică de familie în satul Crocmaz, în sudul Moldovei, în regiunea Ștefan Vodă.', 'en', 'A small family winery in the village of Crocmaz in southern Moldova, in the Ștefan Vodă region.'))
on conflict (id) do nothing;

insert into public.wines (id, winery_id, name, type, grape_variety, vintage, rating, avg_price_lei, image_url, description) values
  (1, 1, 'Fetească Neagră Premium', 'red_dry', 'Fetească Neagră', 2020, 4.8, 180, '',
   jsonb_build_object('ru', 'Богатый аромат спелой вишни, чернослива и сафьяновой кожи.', 'ro', 'Arome bogate de cireșe coapte, prune uscate și piele fină.', 'en', 'Rich aromas of ripe cherry, prunes and fine leather.')),
  (2, 2, 'Viorica de Purcari', 'white_dry', 'Viorica', 2023, 4.9, 145, '',
   jsonb_build_object('ru', 'Свежий вкус с нотами муската, цитрусовых и белых цветов.', 'ro', 'Gust proaspăt cu note de muscat, citrice și flori albe.', 'en', 'Fresh taste with notes of muscat, citrus and white flowers.')),
  (3, 1, 'Rară Neagră Taraboste', 'red_dry', 'Rară Neagră', 2019, 4.7, 320, '',
   jsonb_build_object('ru', 'Выдержанное вино с оттенками сухофруктов и дуба.', 'ro', 'Vin maturat cu nuanțe de fructe uscate și stejar.', 'en', 'An aged wine with hints of dried fruit and oak.')),
  (4, 3, 'Cricova Brut', 'sparkling', 'Chardonnay, Pinot Noir', 2021, 4.6, 210, '',
   jsonb_build_object('ru', 'Классическое игристое с тонкой перлажью, нотами яблока и бриоши.', 'ro', 'Spumant clasic cu perlaj fin, note de măr și brioșă.', 'en', 'A classic sparkling wine with fine bubbles and notes of apple and brioche.')),
  (5, 5, 'Rosé de Mimi', 'rose_dry', 'Pinot Noir', 2023, 4.5, 190, '',
   jsonb_build_object('ru', 'Лёгкое розовое с ароматом клубники, малины и цветов.', 'ro', 'Rose ușor cu arome de căpșuni, zmeură și flori.', 'en', 'A light rosé with aromas of strawberry, raspberry and flowers.')),
  (6, 6, 'Asconi Sauvignon Blanc', 'white_dry', 'Sauvignon Blanc', 2023, 4.4, 130, '',
   jsonb_build_object('ru', 'Хрустящее белое с нотами крыжовника, лайма и свежей травы.', 'ro', 'Alb crocant cu note de agrișe, lime și iarbă proaspătă.', 'en', 'A crisp white with notes of gooseberry, lime and fresh grass.')),
  (7, 7, 'Et Cetera Merlot', 'red_dry', 'Merlot', 2020, 4.6, 250, '',
   jsonb_build_object('ru', 'Мягкое бархатистое красное со спелой сливой и шоколадом.', 'ro', 'Roșu moale și catifelat, cu prune coapte și ciocolată.', 'en', 'A soft, velvety red with ripe plum and chocolate.')),
  (8, 4, 'Mileștii Mici Cabernet Sauvignon', 'red_dry', 'Cabernet Sauvignon', 2018, 4.7, 280, '',
   jsonb_build_object('ru', 'Выдержанное в подвалах вино с тонами чёрной смородины и табака.', 'ro', 'Vin maturat în beciuri, cu tonuri de coacăză neagră și tutun.', 'en', 'Aged in underground cellars, with tones of blackcurrant and tobacco.'))
on conflict (id) do nothing;

insert into public.grapes (id, name, color, is_native, aliases, description, taste, sort_order) values
  ('feteasca-neagra', 'Fetească Neagră', 'red', true, '{}'::text[],
   jsonb_build_object('ru', 'Древний местный красный сорт, один из символов молдавского виноделия. Даёт насыщенные вина, которые хорошо раскрываются с выдержкой.', 'ro', 'Soi roșu autohton străvechi, unul dintre simbolurile vinificației moldovenești. Dă vinuri intense, care se dezvoltă frumos la învechire.', 'en', 'An ancient native red grape and one of the symbols of Moldovan winemaking. It gives rich wines that develop beautifully with age.'),
   jsonb_build_object('ru', 'Чернослив, спелая вишня, чёрная смородина, пряности.', 'ro', 'Prune uscate, cireșe coapte, coacăză neagră, condimente.', 'en', 'Prunes, ripe cherry, blackcurrant, spice.'), 10),
  ('rara-neagra', 'Rară Neagră', 'red', true, array['Băbească Neagră']::text[],
   jsonb_build_object('ru', 'Местный красный сорт, в Румынии известный как Бэбяскэ Нягрэ. Даёт лёгкие, мягкие вина с яркой ягодностью.', 'ro', 'Soi roșu autohton, cunoscut în România ca Băbească Neagră. Dă vinuri ușoare, catifelate, cu fructuozitate vie.', 'en', 'A native red grape known in Romania as Băbească Neagră. It makes light, soft wines with bright red fruit.'),
   jsonb_build_object('ru', 'Вишня, красные ягоды, лёгкие пряные ноты.', 'ro', 'Vișine, fructe roșii, note ușor condimentate.', 'en', 'Sour cherry, red berries, a hint of spice.'), 20),
  ('feteasca-alba', 'Fetească Albă', 'white', true, '{}'::text[],
   jsonb_build_object('ru', 'Старинный местный белый сорт. Вина получаются лёгкими и изящными, часто с тонким цветочным ароматом.', 'ro', 'Soi alb autohton vechi. Dă vinuri ușoare și elegante, adesea cu o aromă florală delicată.', 'en', 'An old native white grape producing light, elegant wines, often with a delicate floral aroma.'),
   jsonb_build_object('ru', 'Белые цветы, зелёное яблоко, персик.', 'ro', 'Flori albe, măr verde, piersică.', 'en', 'White flowers, green apple, peach.'), 30),
  ('feteasca-regala', 'Fetească Regală', 'white', true, '{}'::text[],
   jsonb_build_object('ru', 'Белый сорт, появившийся в XX веке как потомок Фетяски Албэ. Свежий и универсальный — от сухих вин до игристых.', 'ro', 'Soi alb apărut în secolul XX, descendent al Feteascăi Albe. Proaspăt și versatil — de la vinuri seci la spumante.', 'en', 'A white grape that appeared in the 20th century as a descendant of Fetească Albă. Fresh and versatile — from dry wines to sparkling.'),
   jsonb_build_object('ru', 'Цитрусы, груша, свежескошенная трава.', 'ro', 'Citrice, pară, iarbă proaspăt cosită.', 'en', 'Citrus, pear, freshly cut grass.'), 40),
  ('viorica', 'Viorica', 'white', true, '{}'::text[],
   jsonb_build_object('ru', 'Ароматный белый сорт, выведенный в Молдове во второй половине XX века. Узнаётся по яркому мускатному аромату.', 'ro', 'Soi alb aromat, creat în Moldova în a doua jumătate a secolului XX. Se recunoaște după aroma intensă de muscat.', 'en', 'An aromatic white grape bred in Moldova in the second half of the 20th century, recognisable by its vivid muscat aroma.'),
   jsonb_build_object('ru', 'Мускат, липа, цитрусы, тропические фрукты.', 'ro', 'Muscat, tei, citrice, fructe tropicale.', 'en', 'Muscat, linden blossom, citrus, tropical fruit.'), 50),
  ('cabernet-sauvignon', 'Cabernet Sauvignon', 'red', false, '{}'::text[],
   jsonb_build_object('ru', 'Самый известный красный сорт в мире и один из самых распространённых в Молдове. Плотные, танинные вина для выдержки.', 'ro', 'Cel mai cunoscut soi roșu din lume și unul dintre cele mai răspândite în Moldova. Vinuri dense, taninoase, potrivite pentru învechire.', 'en', 'The world''s best-known red grape and one of the most planted in Moldova. Full, tannic wines built for ageing.'),
   jsonb_build_object('ru', 'Чёрная смородина, вишня, табак, кедр.', 'ro', 'Coacăză neagră, cireșe, tutun, cedru.', 'en', 'Blackcurrant, cherry, tobacco, cedar.'), 60),
  ('merlot', 'Merlot', 'red', false, '{}'::text[],
   jsonb_build_object('ru', 'Мягкий и бархатистый красный сорт, часто встречается в купажах с Каберне.', 'ro', 'Soi roșu moale și catifelat, des întâlnit în cupaje cu Cabernet.', 'en', 'A soft, velvety red grape, often blended with Cabernet.'),
   jsonb_build_object('ru', 'Слива, вишня, шоколад.', 'ro', 'Prune, cireșe, ciocolată.', 'en', 'Plum, cherry, chocolate.'), 70),
  ('pinot-noir', 'Pinot Noir', 'red', false, '{}'::text[],
   jsonb_build_object('ru', 'Капризный, но изысканный красный сорт. Даёт лёгкие элегантные вина и служит основой многих игристых.', 'ro', 'Soi roșu pretențios, dar rafinat. Dă vinuri ușoare și elegante și stă la baza multor spumante.', 'en', 'A demanding but refined red grape, giving light, elegant wines and forming the base of many sparkling wines.'),
   jsonb_build_object('ru', 'Клубника, малина, вишня, лесные ноты.', 'ro', 'Căpșuni, zmeură, cireșe, note de pădure.', 'en', 'Strawberry, raspberry, cherry, forest floor.'), 80),
  ('chardonnay', 'Chardonnay', 'white', false, '{}'::text[],
   jsonb_build_object('ru', 'Один из самых популярных белых сортов в мире. Бывает и свежим, и насыщенным после выдержки в дубе; основа классических игристых.', 'ro', 'Unul dintre cele mai populare soiuri albe din lume. Poate fi proaspăt sau bogat după învechire în stejar; bază pentru spumantele clasice.', 'en', 'One of the world''s most popular white grapes — fresh or rich after oak ageing, and a base for classic sparkling wines.'),
   jsonb_build_object('ru', 'Яблоко, груша, цитрусы, ваниль (после дуба).', 'ro', 'Măr, pară, citrice, vanilie (după stejar).', 'en', 'Apple, pear, citrus, vanilla (when oaked).'), 90),
  ('sauvignon-blanc', 'Sauvignon Blanc', 'white', false, '{}'::text[],
   jsonb_build_object('ru', 'Свежий ароматный белый сорт с яркой кислотностью.', 'ro', 'Soi alb proaspăt și aromat, cu aciditate vie.', 'en', 'A fresh, aromatic white grape with lively acidity.'),
   jsonb_build_object('ru', 'Крыжовник, лайм, зелёный перец, трава.', 'ro', 'Agrișe, lime, ardei verde, iarbă.', 'en', 'Gooseberry, lime, green pepper, grass.'), 100),
  ('floricica', 'Floricica', 'white', true, '{}'::text[],
   jsonb_build_object('ru', 'Белый сорт молдавской селекции, устойчивый к морозам и болезням винограда. Из него делают свежие ароматные вина.', 'ro', 'Soi alb de selecție moldovenească, rezistent la ger și la bolile viței-de-vie. Din el se fac vinuri proaspete și aromate.', 'en', 'A white grape bred in Moldova, resistant to frost and vine diseases. It makes fresh, aromatic wines.'),
   jsonb_build_object('ru', 'Белые цветы, цитрусы, лёгкие мускатные ноты.', 'ro', 'Flori albe, citrice, note ușoare de muscat.', 'en', 'White flowers, citrus, a light muscat touch.'), 110),
  ('codrinschi', 'Codrinschi', 'red', true, array['Codrinschii', 'Codrinski']::text[],
   jsonb_build_object('ru', 'Красный сорт молдавской селекции, названный в честь лесов Кодр. Устойчив к морозам, даёт вина глубокого цвета.', 'ro', 'Soi roșu de selecție moldovenească, numit după codrii Moldovei. Rezistent la ger, dă vinuri de culoare intensă.', 'en', 'A red grape bred in Moldova and named after the Codru forests. Frost-hardy, it gives deeply coloured wines.'),
   jsonb_build_object('ru', 'Тёмные ягоды, вишня, лёгкая пряность.', 'ro', 'Fructe de pădure negre, vișine, o notă ușor condimentată.', 'en', 'Dark berries, cherry, a light spice.'), 120),
  ('alb-de-onitcani', 'Alb de Onițcani', 'white', true, array['Alb de Onitcani']::text[],
   jsonb_build_object('ru', 'Белый сорт молдавской селекции. Встречается редко — в основном у небольших виноделен.', 'ro', 'Soi alb de selecție moldovenească. Se întâlnește rar — mai ales la vinăriile mici.', 'en', 'A white grape bred in Moldova. It is rare and found mostly at small wineries.'),
   jsonb_build_object('ru', 'Свежие фрукты, цветы, живая кислотность.', 'ro', 'Fructe proaspete, flori, aciditate vie.', 'en', 'Fresh fruit, flowers, lively acidity.'), 130),
  ('tamaioasa-romaneasca', 'Tămâioasă Românească', 'white', true, array['Tamaioasa Romaneasca', 'Tămâioasă']::text[],
   jsonb_build_object('ru', 'Старинный ароматный белый сорт региона, родственник Муската. Известен ярким, почти «ладанным» ароматом.', 'ro', 'Soi alb aromat vechi al regiunii, rudă cu Muscatul. Cunoscut pentru aroma intensă, aproape de tămâie.', 'en', 'An old aromatic white grape of the region, related to Muscat, known for its intense, almost incense-like aroma.'),
   jsonb_build_object('ru', 'Мускат, роза, мёд, базилик.', 'ro', 'Muscat, trandafir, miere, busuioc.', 'en', 'Muscat, rose, honey, basil.'), 140),
  ('saperavi', 'Saperavi', 'red', false, '{}'::text[],
   jsonb_build_object('ru', 'Грузинский сорт с окрашенной мякотью, широко распространённый в Молдове. Даёт очень тёмные, насыщенные вина с хорошей кислотностью.', 'ro', 'Soi georgian cu pulpă colorată, larg răspândit în Moldova. Dă vinuri foarte închise la culoare, intense, cu aciditate bună.', 'en', 'A Georgian grape with coloured flesh, widely planted in Moldova. It gives very dark, intense wines with good acidity.'),
   jsonb_build_object('ru', 'Ежевика, чернослив, тёмная вишня, специи.', 'ro', 'Mure, prune uscate, cireșe negre, condimente.', 'en', 'Blackberry, prune, dark cherry, spice.'), 150),
  ('aligote', 'Aligoté', 'white', false, array['Aligote']::text[],
   jsonb_build_object('ru', 'Белый сорт из Бургундии, давно и широко выращивается в Молдове. Лёгкие, свежие вина с яркой кислотностью.', 'ro', 'Soi alb din Burgundia, cultivat de mult și pe scară largă în Moldova. Vinuri ușoare și proaspete, cu aciditate vie.', 'en', 'A white grape from Burgundy, long and widely grown in Moldova. Light, fresh wines with bright acidity.'),
   jsonb_build_object('ru', 'Зелёное яблоко, лимон, полевые цветы.', 'ro', 'Măr verde, lămâie, flori de câmp.', 'en', 'Green apple, lemon, meadow flowers.'), 160),
  ('riesling', 'Riesling', 'white', false, array['Rhine Riesling', 'Riesling de Rin']::text[],
   jsonb_build_object('ru', 'Благородный белый сорт из Германии: от сухих до сладких вин, с высокой кислотностью и хорошим потенциалом выдержки.', 'ro', 'Soi alb nobil din Germania: de la vinuri seci la dulci, cu aciditate ridicată și bun potențial de învechire.', 'en', 'A noble white grape from Germany, from dry to sweet styles, with high acidity and good ageing potential.'),
   jsonb_build_object('ru', 'Лайм, зелёное яблоко, персик, минеральность.', 'ro', 'Lime, măr verde, piersică, mineralitate.', 'en', 'Lime, green apple, peach, minerality.'), 170),
  ('pinot-blanc', 'Pinot Blanc', 'white', false, array['Pinot Bianco', 'Pinot Alb']::text[],
   jsonb_build_object('ru', 'Белая разновидность Пино: мягкие, округлые вина с умеренной кислотностью, часто используется для игристых.', 'ro', 'Varietatea albă a Pinot-ului: vinuri moi, rotunde, cu aciditate moderată, des folosită pentru spumante.', 'en', 'The white member of the Pinot family: soft, round wines with moderate acidity, often used for sparkling wine.'),
   jsonb_build_object('ru', 'Груша, яблоко, миндаль.', 'ro', 'Pară, măr, migdale.', 'en', 'Pear, apple, almond.'), 180),
  ('pinot-gris', 'Pinot Gris', 'white', false, array['Pinot Grigio']::text[],
   jsonb_build_object('ru', 'Сорт с розовато-серой кожицей. В лёгком стиле известен как Пино Гриджо, в насыщенном — как Пино Гри.', 'ro', 'Soi cu pielița roz-cenușie. În stil ușor e cunoscut ca Pinot Grigio, în stil bogat — ca Pinot Gris.', 'en', 'A grape with pinkish-grey skin, known as Pinot Grigio in its light style and Pinot Gris in its richer style.'),
   jsonb_build_object('ru', 'Груша, дыня, цитрусы, лёгкая пряность.', 'ro', 'Pară, pepene galben, citrice, o notă ușor condimentată.', 'en', 'Pear, melon, citrus, a light spice.'), 190),
  ('syrah', 'Syrah', 'red', false, array['Shiraz']::text[],
   jsonb_build_object('ru', 'Красный сорт из долины Роны (он же Шираз): плотные вина с тёмными ягодами и перечными нотами.', 'ro', 'Soi roșu din valea Ronului (numit și Shiraz): vinuri dense, cu fructe negre și note de piper.', 'en', 'A red grape from the Rhône valley (also called Shiraz): full wines with dark fruit and peppery notes.'),
   jsonb_build_object('ru', 'Ежевика, слива, чёрный перец, копчёности.', 'ro', 'Mure, prune, piper negru, note afumate.', 'en', 'Blackberry, plum, black pepper, smoky notes.'), 200),
  ('malbec', 'Malbec', 'red', false, array['Côt']::text[],
   jsonb_build_object('ru', 'Красный сорт французского происхождения, прославленный Аргентиной: сочные, тёмные, мягкие вина.', 'ro', 'Soi roșu de origine franceză, devenit celebru în Argentina: vinuri suculente, închise și catifelate.', 'en', 'A red grape of French origin made famous by Argentina: juicy, dark, smooth wines.'),
   jsonb_build_object('ru', 'Слива, ежевика, какао, фиалка.', 'ro', 'Prune, mure, cacao, violete.', 'en', 'Plum, blackberry, cocoa, violet.'), 210),
  ('tempranillo', 'Tempranillo', 'red', false, '{}'::text[],
   jsonb_build_object('ru', 'Главный красный сорт Испании (Риоха): вина средней насыщенности, хорошо сочетающиеся с выдержкой в дубе.', 'ro', 'Principalul soi roșu al Spaniei (Rioja): vinuri de corpolență medie, care se potrivesc bine cu învechirea în stejar.', 'en', 'Spain''s leading red grape (Rioja): medium-bodied wines that take well to oak ageing.'),
   jsonb_build_object('ru', 'Вишня, томлёная слива, кожа, ваниль.', 'ro', 'Vișine, prune coapte, piele, vanilie.', 'en', 'Cherry, stewed plum, leather, vanilla.'), 220),
  ('albarino', 'Albariño', 'white', false, array['Albarino', 'Alvarinho']::text[],
   jsonb_build_object('ru', 'Белый сорт с атлантического побережья Испании и Португалии: свежие ароматные вина, отлично подходящие к морепродуктам.', 'ro', 'Soi alb de pe coasta atlantică a Spaniei și Portugaliei: vinuri proaspete și aromate, excelente cu fructe de mare.', 'en', 'A white grape from the Atlantic coast of Spain and Portugal: fresh, aromatic wines that are great with seafood.'),
   jsonb_build_object('ru', 'Персик, абрикос, цитрусы, солёная свежесть.', 'ro', 'Piersică, caisă, citrice, prospețime sărată.', 'en', 'Peach, apricot, citrus, saline freshness.'), 230),
  ('glera', 'Glera', 'white', false, array['Prosecco']::text[],
   jsonb_build_object('ru', 'Итальянский белый сорт, из которого делают Просекко: лёгкие, фруктовые игристые вина.', 'ro', 'Soi alb italian din care se face Prosecco: vinuri spumante ușoare și fructuoase.', 'en', 'The Italian white grape behind Prosecco: light, fruity sparkling wines.'),
   jsonb_build_object('ru', 'Зелёное яблоко, груша, белые цветы.', 'ro', 'Măr verde, pară, flori albe.', 'en', 'Green apple, pear, white flowers.'), 240),
  ('bastardo', 'Bastardo', 'red', false, array['Bastardo Magaraci', 'Trousseau']::text[],
   jsonb_build_object('ru', 'Красный сорт португальского происхождения (во Франции — Труссо). В нашем регионе известен по сорту Бастардо Магарачский.', 'ro', 'Soi roșu de origine portugheză (în Franța — Trousseau). În regiunea noastră este cunoscut prin soiul Bastardo Magaraci.', 'en', 'A red grape of Portuguese origin (Trousseau in France), known in our region through the Bastardo Magaraci variety.'),
   jsonb_build_object('ru', 'Красные ягоды, вишня, лёгкие землистые ноты.', 'ro', 'Fructe roșii, vișine, note ușor teroase.', 'en', 'Red berries, cherry, light earthy notes.'), 250)
on conflict (id) do nothing;

insert into public.routes (id, title, description, duration, winery_ids, sort_order) values
  ('codru-cellars', jsonb_build_object('ru', 'Подземные галереи Кодр', 'ro', 'Galeriile subterane din Codru', 'en', 'Underground cellars of Codru'),
   jsonb_build_object('ru', 'Три винодельни в получасе от Кишинёва. Крикова и Милештий Мичь знамениты подземными винными городами, а Кожушна — уютными подвалами и коллекцией вин.', 'ro', 'Trei vinării la jumătate de oră de Chișinău. Cricova și Mileștii Mici sunt renumite pentru orașele subterane ale vinului, iar Cojușna — pentru cramele primitoare și colecția de vinuri.', 'en', 'Three wineries within half an hour of Chișinău. Cricova and Mileștii Mici are famous for their underground wine cities, Cojușna for its cosy cellars and wine collection.'),
   jsonb_build_object('ru', '1 день', 'ro', '1 zi', 'en', '1 day'), array[(select id from public.wineries where name = 'Cricova'), (select id from public.wineries where name = 'Château Cojușna'), (select id from public.wineries where name = 'Mileștii Mici')]::bigint[], 10),
  ('castles-near-chisinau', jsonb_build_object('ru', 'Замки и шато у Кишинёва', 'ro', 'Castele și conace lângă Chișinău', 'en', 'Castles and estates near Chișinău'),
   jsonb_build_object('ru', 'Замок Мими конца XIX века, семейная Carlevana с дегустациями по сеансам и Asconi с рестораном в традиционном стиле — всё в пределах часа езды.', 'ro', 'Castelul Mimi de la sfârșitul secolului XIX, vinăria de familie Carlevana cu degustări pe ore fixe și Asconi cu restaurant în stil tradițional — toate la mai puțin de o oră de drum.', 'en', 'The late-19th-century Mimi castle, the family-run Carlevana with scheduled tastings, and Asconi with its traditional-style restaurant — all within an hour''s drive.'),
   jsonb_build_object('ru', '1 день', 'ro', '1 zi', 'en', '1 day'), array[(select id from public.wineries where name = 'Castel Mimi'), (select id from public.wineries where name = 'Carlevana Winery'), (select id from public.wineries where name = 'Asconi')]::bigint[], 20),
  ('orhei', jsonb_build_object('ru', 'Орхей: Вартели и Бранешть', 'ro', 'Orhei: Vartely și Brănești', 'en', 'Orhei: Vartely and Brănești'),
   jsonb_build_object('ru', 'Современный комплекс Château Vartely и подвалы Бранешть в бывших известняковых выработках. Поездку легко совместить с Орхеюл Векь.', 'ro', 'Complexul modern Château Vartely și cramele Brănești din fostele mine de calcar. Excursia se combină ușor cu Orheiul Vechi.', 'en', 'The modern Château Vartely complex and the Brănești cellars in former limestone mines. Easy to combine with Orheiul Vechi.'),
   jsonb_build_object('ru', 'Полдня', 'ro', 'O jumătate de zi', 'en', 'Half a day'), array[(select id from public.wineries where name = 'Château Vartely'), (select id from public.wineries where name = 'Pivnițele Brănești')]::bigint[], 30),
  ('south-purcari', jsonb_build_object('ru', 'Юг: Пуркарь и Штефан-Водэ', 'ro', 'Sudul: Purcari și Ștefan Vodă', 'en', 'The south: Purcari and Ștefan Vodă'),
   jsonb_build_object('ru', 'Историческое шато Пуркарь, соседние винодельни села Пуркарь и семейная Et Cetera в Крокмазе. Около двух часов от Кишинёва — удобнее с ночёвкой.', 'ro', 'Istoricul Château Purcari, vinăriile vecine din satul Purcari și vinăria de familie Et Cetera din Crocmaz. Circa două ore de Chișinău — mai comod cu înnoptare.', 'en', 'The historic Château Purcari, neighbouring wineries in Purcari village and the family-run Et Cetera in Crocmaz. About two hours from Chișinău, best with an overnight stay.'),
   jsonb_build_object('ru', '1–2 дня', 'ro', '1–2 zile', 'en', '1–2 days'), array[(select id from public.wineries where name = 'Château Purcari'), (select id from public.wineries where name = 'Timbrus Purcari Estate'), (select id from public.wineries where name = 'Domeniile Pripa'), (select id from public.wineries where name = 'Et Cetera')]::bigint[], 40),
  ('valul-lui-traian', jsonb_build_object('ru', 'Валул луй Траян: юго-запад', 'ro', 'Valul lui Traian: sud-vest', 'en', 'Valul lui Traian: the south-west'),
   jsonb_build_object('ru', 'Винодельни исторического региона Валул луй Траян у реки Прут: Fautor в Тигечь, Gitana в Плопь и NOVAK в Лингуре. Посещения — по договорённости, звоните заранее.', 'ro', 'Vinăriile regiunii istorice Valul lui Traian, lângă Prut: Fautor la Tigheci, Gitana la Plopi și NOVAK la Lingura. Vizitele — cu programare, sunați din timp.', 'en', 'Wineries of the historic Valul lui Traian region near the Prut: Fautor in Tigheci, Gitana in Plopi and NOVAK in Lingura. Visits by arrangement — call ahead.'),
   jsonb_build_object('ru', '1 день', 'ro', '1 zi', 'en', '1 day'), array[(select id from public.wineries where name = 'Fautor Winery'), (select id from public.wineries where name = 'Gitana Winery'), (select id from public.wineries where name = 'NOVAK Winery')]::bigint[], 50)
on conflict (id) do nothing;

-- id заданы вручную — сдвигаем счётчики, чтобы новые записи не конфликтовали
select setval(pg_get_serial_sequence('public.wineries', 'id'), (select max(id) from public.wineries));
select setval(pg_get_serial_sequence('public.wines', 'id'), (select max(id) from public.wines));
