name: wine_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  url_launcher: ^6.3.2
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
