-- Схема каталога: винодельни и вина.
-- Чтение открыто всем (каталог публичный), изменять данные можно только
-- через панель Supabase или сервисным ключом — из приложения записи нет.

create table public.wineries (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  region      text,
  latitude    double precision not null check (latitude between -90 and 90),
  longitude   double precision not null check (longitude between -180 and 180),
  created_at  timestamptz not null default now()
);

create table public.wines (
  id             bigint generated by default as identity primary key,
  winery_id      bigint not null references public.wineries (id) on delete cascade,
  name           text not null,
  -- Коды типов, которые понимает приложение (см. lib/l10n/wine_type_labels.dart)
  type           text not null check (type in ('red_dry', 'white_dry', 'rose_dry', 'sparkling')),
  grape_variety  text not null default '',
  vintage        integer check (vintage between 1900 and 2100),
  rating         numeric(2, 1) check (rating between 0 and 5),
  avg_price_lei  numeric(10, 2) check (avg_price_lei >= 0),
  image_url      text not null default '',
  -- Описание на нескольких языках: {"ru": "...", "ro": "...", "en": "..."}
  description    jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now()
);

create index wines_winery_id_idx on public.wines (winery_id);

-- Row Level Security: без политик таблицы закрыты для публичного ключа
alter table public.wineries enable row level security;
alter table public.wines enable row level security;

create policy "Винодельни видны всем"
  on public.wineries for select
  to anon, authenticated
  using (true);

create policy "Вина видны всем"
  on public.wines for select
  to anon, authenticated
  using (true);
